services:
  - type: web
    name: mini-sql-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.web_app
    envVars:
      - key: PORT
        value: 10000